#!/usr/bin/env python 
import sys, os, re, operator, functools

if '-v' in sys.argv:
    print "$Id: jplotter,v 1.3 2014-08-08 15:38:40 jive_cc Exp $"
    sys.exit( 0 )

if '-h' in sys.argv:
    print "Usage: {0} [-h] [-d] [-v]".format(os.path.basename(sys.argv[0]))
    print """
    where:
        -h  print this message and exit"
        -v  print version and exit
        -d  turn on debug output [prints stack trace upon error]
        ppgplot=/path/to/home/of{/ppgplot/__init__.py}
            load ppgplot module from '/path/to/home/of' if that path exists
"""
    sys.exit( 0 )

# look for an entries "ppgplot=..." and insert them into the system path
map(lambda mo: sys.path.insert(0, mo.group(1)) if os.path.isdir(mo.group(1)) else None,
    filter(operator.truth, map(re.compile(r'^ppgplot=(.+)$').search, sys.argv[1:])))

# we run interactively from the commandline
import command, jplotter
jplotter.run_plotter(command.readkbd("jcli"), debug=('-d' in sys.argv))
