name: Test Build and Publish

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - test-pypi*

jobs:
  build_package:
    name: Build universal wheel and sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel and sdist
        run: python -m build

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: jiveplot-wheel
          path: dist/*.whl

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: jiveplot-sdist
          path: dist/*.tar.gz

  test_publish:
    name: Test Publish to Test PyPI
    needs: build_package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Flatten artifacts
        run: |
          find dist/ -name "*.whl" -exec mv {} dist/ \;
          find dist/ -name "*.tar.gz" -exec mv {} dist/ \;
          find dist/ -mindepth 1 -type d -exec rm -rf {} + || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Twine
        run: pip install twine

      - name: Verify distributions
        run: |
          ls -la dist/
          twine check dist/*

      - name: Publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository testpypi dist/*
